name: GK-Nexus

services:
  postgres:
    image: postgres
    container_name: GK-Nexus-postgres
    environment:
      POSTGRES_DB: GK-Nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - GK-Nexus_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  GK-Nexus_postgres_data: